apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: my-prometheus
spec:
  replicas: 1
  version: v2.30.3
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: standard
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
  ruleSelector:
    matchLabels:
      role: prometheus
  serviceAccountName: prometheus-k8s
  securityContext:
    fsGroup: 2000
  serviceMonitorSelector:
    matchLabels:
      role: prometheus
  resources:
    requests:
      memory: 400Mi
